language: r
cache:
- packages
sudo: required
dist: "trusty"
warnings_are_errors: false

before_install:
  - R -e 'source("https://install-github.me/r-lib/remotes")'
  - Rscript -e 'remotes::install_github("diazrenata/replicatebecs")'


matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - R CMD INSTALL .
