language: r
cache:
- packages
sudo: required
dist: "trusty"
warnings_are_errors: false

r_github_packages: diazrenata/replicatebecs

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - R CMD INSTALL .
